### ISSUE TITLE
提前终止训练？

### ISSUE THREAD

**Issue by gunquxuexia** [Rooooyy/HiTIN#3]
为什么会提前终止训练？
(HIN) F:\paperAndcode\code\HiTIN-master\HiTIN-master\models\structure_model>python train.py -cfg F:\paperAndcode\code\HiTIN-master\HiTIN-master\config\tin-wos-bert.json -k 2 -b 12 -hd 300 -lr 1e-4 -tp sum
{'batch_size': 12,
 'begin_time': '0410_1111_',
 'ckpt_dir': 'ckpt',
 'classification_threshold': 0.5,
 'config_file': 'F:\\paperAndcode\\code\\HiTIN-master\\HiTIN-master\\config\\tin-wos-bert.json',
 'final_dropout': 0.5,
 'hidden_dim': 300,
 'hierar_penalty': 0,
 'l2rate': 0,
 'learning_rate': 0.0001,
 'load_pretrained': False,
 'log_dir': 'log',
 'num_mlp_layers': 2,
 'tree_depth': 2,
 'tree_pooling_type': 'sum'}
'CUDA_VISIBLE_DEVICES' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Loading files for TRAIN Dataset...
Loading files for VAL Dataset...
Loading files for TEST Dataset...
Coding tree generation costs time of 0.7005748748779297

**Comment by Rooooyy** [comment]
你好，这种情况有几种可能：
1.你的实验环境没有CUDA，请自行百度如何安装 
2. 我的代码设置CUDA_VISIBLE_DEVICE=0，而你的运行环境CUDA设备编号不是从0开始的，这种情况多见于多人共用同一台机器，请自行修改train.py第242行代码和config文件中的visible_device_list

**Comment by z20021009** [comment]
> 为什么会提前终止训练？（HIN） F：\paperAndcode\code\HiTIN-master\HiTIN-master\models\structure_model>python train.py -cfg F：\paperAndcode\code\code\HiTIN-master\HiTIN-master\config\tin-wos-bert.json -k 2 -b 12 -hd 300 -lr 1e-4 -tp sum {'batch_size'： 12， 'begin_time'： '0410_1111_'， 'ckpt_dir'： 'ckpt'， 'classification_threshold'： 0.5， 'config_file'： 'F：\paperAndcode\code\HiTIN-master\HiTIN-master\config\tin-wos-bert.json'， 'final_dropout'： 0.5， 'hidden_dim'： 300， 'hierar_penalty'： 0， 'l2rate'： 0， 'learning_rate'： 0.0001， 'load_pretrained'： false， 'log_dir'： 'log'， 'num_mlp_layers'： 2， 'tree_depth'： 2， 'tree_pooling_type'： 'sum'} 'CUDA_VISIBLE_DEVICES' 不是内部或外部命令，也不是可运行的程序 或批处理文件。正在加载 TRAIN 数据集的文件...正在加载 VAL 数据集的文件...正在加载 TEST 数据集的文件...编码树生成耗时为 0.7005748748779297

 您好 
请问解决了吗？
