### ISSUE TITLE
Doesn't start training

### ISSUE THREAD

**Issue by karthikdatta98** [Rooooyy/HiTIN#5]
{'batch_size': 12,
 'begin_time': '1106_0159_',
 'ckpt_dir': 'ckpt',
 'classification_threshold': 0.5,
 'config_file': 'config/tin-wos-bert.json',
 'final_dropout': 0.5,
 'hidden_dim': 768,
 'hierar_penalty': 0,
 'l2rate': 0,
 'learning_rate': 0.0001,
 'load_pretrained': False,
 'log_dir': 'log',
 'num_mlp_layers': 2,
 'tree_depth': 2,
 'tree_pooling_type': 'sum'}
Loading files for TRAIN Dataset...
Loading files for VAL Dataset...
Loading files for TEST Dataset...
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 420M/420M [00:10<00:00, 41.5MB/s]
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertTextEncoder: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertTextEncoder from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertTextEncoder from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Coding tree generation costs time of 0.33737921714782715

The code gets killed after this. No error msg or anything. Any idea?

**Comment by Rooooyy** [comment]
Hi, there. Comment lines 59-61 in tin.py please.
